EcommerceWeb/Areas/Admin/Controllers/ProductController.cs
using EcommerceWEB.DataAccess.Repository.IRepo;
using EcommerceWEB.Models.Models;
using EcommerceWEB.Models.ViewModels;
using EcommerceWEB.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EcommerceWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class ProductController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _webHostEnvironment;

    public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
    {
        _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
        _webHostEnvironment = webHostEnvironment ?? throw new ArgumentNullException(nameof(webHostEnvironment));
    }


    #region Fetch Product
    public IActionResult Index()
    {
        List<Product> objProductList = _unitOfWork.ProductRepository.GetAll(includeProperties: "Category", null).OrderBy(x => x.Title).ToList();
        return View(objProductList);
    }
    #endregion

    #region Update Insert Product
    public IActionResult Upsert(Guid? id)
    {
        ProductVM productVM = new()
        {
            CategoryList = _unitOfWork.CategoryRepository.GetAll(null, null).Select(x => new SelectListItem
            {
                Text = x.CategoryName,
                Value = x.Id.ToString()
            }),

            Product = new Product()
        };

        if (id.HasValue)
        {
            productVM.Product = _unitOfWork.ProductRepository.GetById(x => x.Id == id, includeProperties: "Category");
        }

        return View(productVM);
    }

    [HttpPost]
    public IActionResult Upsert(ProductVM obj, IFormFile file)
    {
        if (_unitOfWork.ProductRepository.GetAll(null, null).Any(x => x.Id != obj.Product.Id && x.Title.Equals(obj.Product.Title, StringComparison.CurrentCultureIgnoreCase)))
        {
            ModelState.AddModelError("Title", "Title already exists");
        }

        if (ModelState.IsValid)
        {
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string productPath = Path.Combine(wwwRootPath, @"images\product\");

                if (!string.IsNullOrEmpty(obj.Product.ImageUrl))
                {
                    var oldImagePath = Path.Combine(wwwRootPath, obj.Product.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }

                obj.Product.ImageUrl = @"\images\product\" + fileName;
            }

            if (obj.Product.Id == Guid.Empty)
            {
                _unitOfWork.ProductRepository.Add(obj.Product);
                TempData["success"] = "Product Created Successfully!";
            }
            else
            {
                _unitOfWork.ProductRepository.Update(obj.Product);
                TempData["success"] = "Product Updated Successfully!";
            }

            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        return View(obj);
    }
    #endregion

    

    #region API Calls
    [HttpGet]
    public ActionResult GetAll()
    {
        List<Product> objProductList = _unitOfWork.ProductRepository.GetAll(includeProperties: "Category", null).OrderBy(x => x.Title).ToList();
        return Json(new { data = objProductList });
    }

    [HttpDelete]
    public ActionResult Delete(Guid id)
    {
        var entity = _unitOfWork.ProductRepository.GetById(x => x.Id == id, includeProperties: "Category");

        if (entity == null)
        {
            return Json(new { success = false, message = "Error while deleting product." });
        }


        string wwwRootPath = _webHostEnvironment.WebRootPath;
        var oldImagePath = Path.Combine(wwwRootPath, entity.ImageUrl.TrimStart('\\'));

        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }

        _unitOfWork.ProductRepository.Remove(entity);
        _unitOfWork.Save();

        return Json(new { success = true, message = "Successfully deleting product." });

    }
    #endregion
}

EcommerceWeb/Areas/Admin/Controllers/UserController.cs
using EcommerceWEB.DataAccess.Repository.IRepo;
using EcommerceWEB.Models.Models;
using EcommerceWEB.Models.ViewModels;
using EcommerceWEB.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EcommerceWeb.Areas.Admin.Controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class UserController : Controller
{
    private readonly UserManager<IdentityUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;
    private readonly IUnitOfWork _unitOfWork;
    public UserController(UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork, RoleManager<IdentityRole> roleManager)
    {
        _unitOfWork = unitOfWork;
        _roleManager = roleManager;
        _userManager = userManager;
    }
    public IActionResult Index()
    {
        return View();
    }
    public IActionResult RoleManagment(string userId)
    {

        RoleManagmentVM RoleVM = new RoleManagmentVM()
        {
            ApplicationUser = _unitOfWork.ApplicationUserRepository.GetById(u => u.Id == userId, includeProperties: "Company"),
            RoleList = _roleManager.Roles.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Name
            }),
            CompanyList = _unitOfWork.CompanyRepository.GetAll(null, null).Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            }),
        };

        RoleVM.ApplicationUser.Role = _userManager.GetRolesAsync(_unitOfWork.ApplicationUserRepository.GetById(u => u.Id == userId, null))
                .GetAwaiter().GetResult().FirstOrDefault();
        return View(RoleVM);
    }

    [HttpPost]
    public IActionResult RoleManagment(RoleManagmentVM roleManagmentVM)
    {

        string oldRole = _userManager.GetRolesAsync(_unitOfWork.ApplicationUserRepository.GetById(u => u.Id == roleManagmentVM.ApplicationUser.Id, null))
                .GetAwaiter().GetResult().FirstOrDefault();

        ApplicationUser applicationUser = _unitOfWork.ApplicationUserRepository.GetById(u => u.Id == roleManagmentVM.ApplicationUser.Id, null);


        if (!(roleManagmentVM.ApplicationUser.Role == oldRole))
        {
            //a role was updated
            if (roleManagmentVM.ApplicationUser.Role == SD.Role_User_Comp)
            {
                applicationUser.CompanyId = roleManagmentVM.ApplicationUser.CompanyId;
            }
            if (oldRole == SD.Role_User_Comp)
            {
                applicationUser.CompanyId = null;
            }
            _unitOfWork.ApplicationUserRepository.Update(applicationUser);
            _unitOfWork.Save();

            _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
            _userManager.AddToRoleAsync(applicationUser, roleManagmentVM.ApplicationUser.Role).GetAwaiter().GetResult();

        }
        else
        {
            if (oldRole == SD.Role_User_Comp && applicationUser.CompanyId != roleManagmentVM.ApplicationUser.CompanyId)
            {
                applicationUser.CompanyId = roleManagmentVM.ApplicationUser.CompanyId;
                _unitOfWork.ApplicationUserRepository.Update(applicationUser);
                _unitOfWork.Save();
            }
        }

        return RedirectToAction("Index");
    }


    [HttpGet]
    public IActionResult GetAll()
    {
        List<ApplicationUser> objUserList = _unitOfWork.ApplicationUserRepository.GetAll(includeProperties: "Company", null).ToList();

        foreach (var user in objUserList)
        {

            user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();

            if (user.Company == null)
            {
                user.Company = new Company()
                {
                    Name = ""
                };
            }
        }

        return Json(new { data = objUserList });
    }


    [HttpPost]
    public IActionResult LockUnlock([FromBody] string id)
    {

        var objFromDb = _unitOfWork.ApplicationUserRepository.GetById(u => u.Id == id, null);
        if (objFromDb == null)
        {
            return Json(new { success = false, message = "Error while Locking/Unlocking" });
        }

        if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
        {
            //user is currently locked and we need to unlock them
            objFromDb.LockoutEnd = DateTime.Now;
        }
        else
        {
            objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
        }
        _unitOfWork.ApplicationUserRepository.Update(objFromDb);
        _unitOfWork.Save();

        return Json(new { success = true, message = "Operation Successful" });
    }


}

EcommerceWeb/Controllers/CategoryController.cs
using EcommerceWEB.DataAccess.Repository.IRepo;
using EcommerceWEB.Models.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace EcommerceWeb.Controllers;

public class CategoryController : Controller
{
    private readonly IUnitOfWork _unitOfWork;

    public CategoryController(IUnitOfWork unitOfWork) 
    {
        _unitOfWork = unitOfWork ?? throw new ArgumentNullException(nameof(unitOfWork));
    }

    #region Fetch Category
    public IActionResult Index()
    {
        List<Category> objCatergoryList = _unitOfWork.CategoryRepository.GetAll().OrderBy(x => x.DisplayOrder).ToList();
        return View(objCatergoryList);
    }
    #endregion

    #region Create Category
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Create(Category obj)
    {
        if (_unitOfWork.CategoryRepository.GetAll().Any(x => x.DisplayOrder == obj.DisplayOrder))
        {
            ModelState.AddModelError("DisplayOrder", "Display Order already exists");
        }

        if (ModelState.IsValid)
        {
            _unitOfWork.CategoryRepository.Add(obj);
            _unitOfWork.Save();
            TempData["success"] = "Category Created Successfully!";
            return RedirectToAction("Index");
        }

        return View();

    }
    #endregion

    #region Update Category
    public ActionResult Update(Guid id)
    {
        Category category = _unitOfWork.CategoryRepository.GetById(x => x.Id == id);

        if (category == null)
        {
            return NotFound();
        }

        return View(category);
    }
    [HttpPost]
    public IActionResult Update(Category obj)
    {
        var existingCategory = _unitOfWork.CategoryRepository.GetById(x => x.Id == obj.Id);

        if (existingCategory != null)
        {
            if (_unitOfWork.CategoryRepository.GetAll().Any(x => x.DisplayOrder == obj.DisplayOrder && x.Id != obj.Id))
            {
                ModelState.AddModelError("DisplayOrder", "Display Order already exists");
            }

            if (ModelState.IsValid)
            {
                existingCategory.CatergoryName = obj.CatergoryName;
                existingCategory.DisplayOrder = obj.DisplayOrder;
                _unitOfWork.Save();
                TempData["success"] = "Category Updated Successfully!";
                return RedirectToAction("Index");
            }
        }

        return View();
    }
    #endregion

    #region Delete Category
    public  ActionResult Delete(Guid id)
    {
        Category category = _unitOfWork.CategoryRepository.GetById(x => x.Id == id);

        if (category == null)
        {
            return NotFound();
        }

        return View(category);
    }
    [HttpPost]
    public IActionResult Delete(Category obj)
    {
        _unitOfWork.CategoryRepository.Remove(obj);
        _unitOfWork.Save();
        TempData["success"] = "Category Deleted Successfully!";
        return RedirectToAction("Index");
    }
    #endregion
}

EcommerceWeb/ViewComponents/ShoppingCartViewComponent.cs
using EcommerceWEB.DataAccess.Repository.IRepo;
using EcommerceWEB.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EcommerceWeb.ViewComponents;

public class ShoppingCartViewComponent : ViewComponent
{
    private readonly IUnitOfWork _unitOfWork;
    public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var claimsIdentity = (ClaimsIdentity)User.Identity;
        var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

        if(claim != null)
        {
            if(HttpContext.Session.GetInt32(SD.SessionCart) == null)
            {
                HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCartRepository.GetAll(null, x => x.ApplicationUserId == claim.Value).Count());
            }
            return View(HttpContext.Session.GetInt32(SD.SessionCart));
        }
        else
        {
            HttpContext.Session.Clear();
            return View(0);
        }
    }
}

EcommerceWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Mister Bookman - Bookstore</title>
    <link href="~/images/product/book.png" rel="icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EcommerceWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" hred="//cdn.datatables.net/2.1.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/product/logo.png" alt="Albertine Books" style="height: 50px;">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item text-light" asp-area="admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-light" asp-area="admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-light" asp-area="admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-light" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-light" asp-area="admin" asp-controller="User" asp-action="Index">Manage User</a>
                                    </li>
                                </ul>
                            </li>
                        }
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="text-center">
            &copy; @DateTime.Now.Year - EcommerceWeb  <a href="https://rivaldonamare.github.io/portofolio/" target="_blank" rel="noopener">rivaldonamare</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"
            integrity="sha384-JzTKjFZcYISeHjKzJePqsDxFMxekQ0F15U9QWRsT7+qjKdeknP1yVJHd8OUz1Gy9"
            crossorigin="anonymous">
    </script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.datatables.net/2.1.0/js/dataTables.min.js"
            integrity="sha384-QwEKZT9YTvYbURrbMmlKhKNMdFZcHlOtLiik9P4kDcnA7ABFrBTH1dpUwnEEMekg"
            crossorigin="anonymous">
    </script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"
            integrity="sha384-qIgKsYP2/JRNgZLo89zM4NU8jAsfu4o9yV4lVIBpHlcRYDJ5YqGj5bcTLCGY7v9b"
            crossorigin="anonymous">
    </script>

    <script src="https://cdn.tiny.cloud/1/6809tp8sid7tzaaze3c87ovis2wjmn7ug9viwegwt9667ewu/tinymce/7/tinymce.min.js"
            integrity="sha384-X2L2OYt+AJKu2dpcyyDYbkKrfYMaVUnmIS5cAbCgKkcRKmZzS3/DYtA4uDWum3Vv"
            referrerpolicy="origin"
            crossorigin="anonymous">
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EcommerceWeb/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"
        integrity="sha384-qIgKsYP2/JRNgZLo89zM4NU8jAsfu4o9yV4lVIBpHlcRYDJ5YqGj5bcTLCGY7v9b"
        crossorigin="anonymous">
</script>

@if (TempData["success"] != null)
{
    <script type="text/javascript">
        const Toast = Swal.mixin({
            toast: true,
            position: "top-end",
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            }
        });
        Toast.fire({
            icon: "success",
            title: "@TempData["success"]"
        });
    </script>
}

@if (TempData["error"] != null)
{
    <script type="text/javascript">
        const Toast = Swal.mixin({
            toast: true,
            position: "top-end",
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.onmouseenter = Swal.stopTimer;
                toast.onmouseleave = Swal.resumeTimer;
            }
        });
        Toast.fire({
            icon: "error",
            title: "@TempData["error"]"
        });
    </script>
}